[package]
name = "downloads-sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
directories = "5.0.1"
rust-ini = "0.19.0"
timer = "0.2.0"
